version: "3"

services:
  mongo-database:
    container_name: mongo-database
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - ./database/data/db:/data/db:rw
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./database/.env
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    
  backend-nodejs:
    container_name: backend-nodejs
    build: ./backend
    ports:
      - 3000:3000
    links:
      - mongo-database
    depends_on: 
      - mongo-database
    restart: always