version: "3"

services:
  mongo-database:
    container_name: mongo-database
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./database/db:/data/db
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./database/.env
    
  backend-nodejs:
    container_name: backend-nodejs
    build: ./backend
    ports:
      - 3000:3000
      - 5000:5000
    links:
      - mongo-database
    depends_on: 
      - mongo-database
    restart: always