version: "3"

services:
  mongo-database:
    container_name: mongo-database
    image: mongo:latest
    # uncomment this if you want know mongodb log
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27018:27017
    volumes:
      - ./database/data/db:/data/db:rw
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./database/.env
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
  
  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./cache/data/db:/data/db:rw
    
  backend-nodejs:
    container_name: backend-nodejs
    build: ./backend
    image: eshya/folkatech-test:latest
    environment:
      SERVER_PORT: 3000
      JWT_SECRET: 'Psstt!!j4n64nKas1t4u!!1!'
      DB_NAME: folkatech
      MONGO_CONNECTIONSTRING: "mongodb://root:password@mongo-database:27017"
      REDIS_PATH: 0
      # Mode Redis => IF 1 -> using redis as cache layer ; ELSE -> just using mongoose layer
      REDISMODE: 1
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      DISPOSABLE_LOGIN_UNAME: root
      DISPOSABLE_LOGIN_PWD: password
    ports:
      - 3000:3000
    links:
      - mongo-database
    depends_on: 
      - mongo-database
    restart: always