const express = require('express');
const router = express.Router();
const c = require('./users.controller');
const {schema} = require('./users.validation');
const {auth, queryCek, schemaCek, paramCek, after} = require('../../helpers');
router.get('/', auth, queryCek, c.findAll);
router.get('/:id', auth, paramCek, c.findById);
router.post('/register', auth, schemaCek(schema), after, c.register);
router.put('/:id', auth, paramCek, c.updateById);
router.delete('/:id', auth, paramCek, c.removeById);
module.exports = router;
